name: Build and Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun extension:build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tv-time-liberator
          path: src/extension/dist/*
          if-no-files-found: error